### ISSUE TITLE
Cool mod, see some progression with the relationships of the sprites, when will ores and alloying come out?

### ISSUE THREAD

**Issue by yoopgim** [LopyLuna/morematerials#3]
the sprites have some amazing textures, and i can see somewhat how the alloy tree looks at parts. i know how you already adressed the whole ore being made for the mod devs. but will you make an addon or funcionality that allows for the mod to be standalone or playable in a way that does not require a defined modpack? it seems like a really good mod but it will likely require some value in of itself if it might be added to modpacks more often. i also just want see the monster of a crafting tree the abiding alloy has.

**Comment by LopyLuna** [comment]
I have plans but I been working on another mod & got kinda burnt out of making this mod but this mod will def get resurfaced when I have the time too!
