### ISSUE TITLE
Some materials don't show textures

### ISSUE THREAD

**Issue by Cakeykins** [LopyLuna/morematerials#4]
Hello, I know you're not updating the mod as you're on hiatus so I understand leaving this question to the wayside, but in the latest 1.19.2 release, a few blocks and ores are completely untextured, I have to test how that looks in world generation if there is any for these ores but I wanted to post this just to reach out, you don't have to answer this, I just wanted to leave this here just in case you DO see this

**Comment by LopyLuna** [comment]
mod is currently outdated and planned to be getting a rewrite
